# SwiftLint Configuration for Design System
# 💻 Credit: Tornike Bardadze

# ----------------------------
# Disabled Rules
# ----------------------------
disabled_rules:
  - trailing_whitespace       # Allow some flexibility for alignment
  - todo                      # Allow TODOs during design system iteration
  - file_length                # UI components often get long (soft warning enforced separately)
  - type_body_length           # Some view structs may be long
  - function_body_length       # Allow long build() or body implementations
  - large_tuple                # Sometimes used for layout tuples

# ----------------------------
# Opt-in Rules (Encourage Clarity)
# ----------------------------
opt_in_rules:
  - empty_count
  - explicit_init
  - operator_usage_whitespace
  - closure_end_indentation
  - vertical_whitespace_between_cases
  - switch_case_alignment
  - indentation_width
  - attributes
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - yoda_condition
  - mark                       # Encourage MARKs to organize code
  - file_header                # Optional headers for components
  - trailing_comma             # Enforce trailing commas for SwiftUI stacks

# ----------------------------
# Analyzer Rules
# ----------------------------
analyzer_rules:
  - explicit_self
  - unused_import
  - force_cast                # Warn for `as!` usage
  - force_try                 # Warn for `try!` usage

# ----------------------------
# Included / Excluded Paths
# ----------------------------
included:
  - Sources
  - DesignSystem
  - Modules

excluded:
  - Pods
  - Carthage
  - DerivedData
  - fastlane
  - Scripts

# ----------------------------
# Rule Configurations
# ----------------------------
line_length:
  warning: 120
  error: 150

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - UI
    - ds   # for design system short tags

type_name:
  max_length: 50

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 12
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5

vertical_whitespace:
  max_empty_lines: 2

# Optional soft warnings for long files / functions
file_length:
  warning: 800    # Soft warning for very long UI components
function_body_length:
  warning: 80     # Soft warning for very long functions (body/build)

# ----------------------------
# Custom Rules
# ----------------------------
custom_rules:
  avoid_force_unwrap:
    included: ".*\\.swift"
    name: "Avoid Force Unwrap / Unsafe Casts"
    regex: "(!\\s*[a-zA-Z0-9_]+\\s*(\\)|,|$))|as!|try!"
    message: "Avoid using force unwraps (!), force casts (as!) or try! in design system code."
    severity: warning
